//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluorography
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string DateOfBirth { get; set; }
        public string Info { get; set; }
        public string Enp { get; set; }
    }
}
