//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluorography
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registr
    {
        public int Number { get; set; }
        public System.DateTime DateSurvay { get; set; }
        public string Street { get; set; }
        public string Selo { get; set; }
        public int ID_patient { get; set; }
    }
}
